apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: my-python-app-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: my-python-app-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: my-python-app-system
