apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "example.com/v1alpha1",
          "kind": "Mypython",
          "metadata": {
            "name": "my-python-sample"
          },
          "spec": {
            "frontend": {
              "image": "quay.io/vishwajitdandage/my-app",
              "imagePullSecrets": [],
              "replicaCount": 1
            }
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.2.0
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
  name: my-python-app.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Mypython
      name: mypythons.example.com
      version: v1alpha1
  description: A simple flask calculator app
  displayName: Flask-App
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - example.com
          resources:
          - mypythons
          - mypythons/status
          - mypythons/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          - persistentvolumes
          - nodes
          - events
          - secrets
          - secrets/finalizers
          - pods
          - pods/finalizers
          - serviceaccounts
          - services
          - configmaps
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - networking.k8s.io
          resources:
          - ingresses
          verbs:
          - '*'
        - apiGroups:
          - security.openshift.io
          resourceNames:
          - anyuid
          resources:
          - securitycontextconstraints
          verbs:
          - use
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          - secrets/finalizers
          - pods
          - pods/finalizers
          - pods/exec
          - pods/log
          - services
          - services/finalizers
          - endpoints
          - persistentvolumeclaims
          - persistentvolumes
          - persistentvolumeclaims/finalizers
          - persistentvolumes/finalizers
          - nodes
          - events
          - configmaps
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: my-python-app
      deployments:
      - name: my-python-app-my-python-app
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: my-python-app
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: my-python-app
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.6.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --metrics-addr=127.0.0.1:8080
                - --enable-leader-election
                - --leader-election-id=mvc-db-app-operator
                env:
                - name: ANSIBLE_GATHERING
                  value: explicit
                - name: OPERATOR_NAME
                  value: my-python-app
                - name: RELATED_IMAGE_FRONTEND
                  value: quay.io/vishwajitdandage/my-app
                image: quay.io/vishwajitdandage/ansible-my-python-app-operator
                imagePullPolicy: Always
                name: manager
                resources: {}
              serviceAccountName: my-python-app
              terminationGracePeriodSeconds: 10
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - python
  - flask
  links:
  - name: My Python App
    url: https://my-python-app.domain
  maintainers:
  - email: vishwajit.vrd@gmail.com
    name: Vishwajit
  maturity: alpha
  provider:
    name: Vishwajit
  version: 0.0.1
